### ISSUE TITLE
Lỗi mất chữ trên một số ứng dụng MIUI

### ISSUE THREAD

**Issue by namnguyen51** [nongthaihoang/google_sans_plus_font#4]
Trên MIUI 12, khi cài font này thì một số ứng dụng như Momo, Fahasa bị lỗi mất chữ trong khi số khác thì vẫn ok.
Thử với 1 số font khác thì không bị hiện tượng này
![Screenshot_2020-07-20-11-33-19-143_com fahasa android fahasa](https://user-images.githubusercontent.com/24988688/87899999-2fce6680-ca7d-11ea-9628-0dabc510460b.jpg)
Không rõ lỗi này do font hay do app, xin nhờ bạn kiểm tra lại.
Ps: font rất đẹp, xin cảm ơn bạn vì đã tạo ra font này :D

**Comment by nongthaihoang** [comment]
Please provide screenshot of installed modules?

**Comment by namnguyen51** [comment]
> Please provide screenshot of installed modules?

![Screenshot_2020-07-20-14-32-04-154_com topjohnwu magisk](https://user-images.githubusercontent.com/24988688/87911430-d1fa4880-ca95-11ea-86f9-ca5b726d6989.jpg)
Trên đầu nhé

**Comment by nongthaihoang** [comment]
This is from mine:
![Screenshot_20200720-124118](https://user-images.githubusercontent.com/43375410/87930099-ac7b3800-cab1-11ea-80aa-7a4346d7372d.png)
![Screenshot_20200720-124059](https://user-images.githubusercontent.com/43375410/87930109-b00ebf00-cab1-11ea-8184-07c00d14e33f.png)

You're better pm me via telegram for further investigation.

**Comment by nongthaihoang** [comment]
And BTW custom rom is not supported. I guess you're on custom one.

**Comment by namnguyen51** [comment]
Uhm, you right. Thanks for your support. I'll try other fonts and roms 👍
