### ISSUE TITLE
Request:Add one more bolder version

### ISSUE THREAD

**Issue by Gluneklairo** [nongthaihoang/google_sans_plus_font#5]
![7fe1edc8ce21441dfb8cc4dd6878464b](https://user-images.githubusercontent.com/65527723/93731568-2342c780-fc00-11ea-868c-836ef79b0b98.jpg)
Bold like this, thx.

**Comment by nongthaihoang** [comment]
Posting a screenshot is not enough. May I know which font is that and where you get it? Any screenshot to compare your font with mine side by side? What's the reason why I should consider your "bold version"? Is "bold strong" not enough for you? Do your eyes have any problems and really want text as bold as possible or it's just your preference? Last but not least, why don't you just use that font if it meets your needs?
